[postgres.latest]
version = "master"
source_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-latest"
data_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-latest/data"
build_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-latest/build"
install_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-latest/install"
bin_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-latest/install/bin"
initialized = false
test_db_created = false


[postgres.pg18]
version = "REL_18_STABLE"
source_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-pg18"
data_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-pg18/data"
build_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-pg18/build"
install_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-pg18/install"
bin_dir = "/Users/nmbr7/.NMBR7/Projects/postgresql/pg-arrow-project/pg_arrow/testdata/postgres-pg18/install/bin"
initialized = false
test_db_created = true
